version: "3.8"
services:
  sns-project-redis:
    container_name: sns-project-redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: devhyuk214/sns-project-redis
    ports:
      - "6379:6379"

  sns-project-database:
    container_name: sns-project-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: devhyuk214/sns-project-database
    environment:
      - MYSQL_DATABASE=sns-project
      - MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  sns-project-zookeeper:
    image: wurstmeister/zookeeper
    container_name: sns-project-zookeeper
    ports:
      - "2181:2181"

  sns-project-kafka:
    image: wurstmeister/kafka
    container_name: sns-project-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: sns-project-zookeeper:2181
      KAFKA_CREATE_TOPICS: "alarm:1:1"
