spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common
jwt:
  secret-key: ${JWT_SECRET_KEY}
  # 30 days
  token.expired-time-ms: 2592000000

---
spring:
  config:
    activate:
      on-profile: common

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns-project
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    consumer:
      properties.spring.json.trusted.packages: "*"
      bootstrap-servers: localhost:9092
      group-id: alarm
      auto-offset-rest: latest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      alarm: alarm

---
spring:
  config:
    activate:
      on-profile: prod
